/**
 * GENERATED by webmcp/evals/storefront-snapshot.mjs — do not edit.
 *
 * The title, description (and any page type's own wording) and output schema of every BestPrice WebMCP
 * tool, as the storefront registers them: bestprice.gr `extra/mcpDiscovery/webmcp-tools.json` (its generated copy of
 * `js/modules/webmcp/tool-catalog.js` and `output-schemas.js`) at 2401b434d2, WebMCP
 * contract 1.9. `contracts.js` publishes them as they are, and
 * `webmcp/test/contract-parity.test.js` compares every published definition with the snapshot.
 */

export const WEBMCP_CONTRACT_VERSION = '1.9';

export const STOREFRONT_CATALOG = {
  search_bestprice: {
    title: 'Search BestPrice products',
    description:
      'Search BestPrice by product name, optionally by price, stock, deals or order. Returns product_id, title, price, store count. Use for named products; not for advice (use get_shopping_decision) or a known id (use get_product_details). Moves this tab.',
    pageDescriptions: {
      product:
        'Search BestPrice by product name, optionally by price, stock, deals or order. Returns product_id, title, price, store count. Use for named products; not for advice (use get_shopping_decision) or this product (use get_page_product). Moves this tab.',
    },
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice search results',
            },
            query: {
              type: 'string',
            },
            results_url: {
              type: 'string',
            },
            page_title: {
              type: ['string', 'null'],
            },
            results_kind: {
              type: 'string',
              enum: ['listing', 'featured', 'product', 'none'],
              description: 'featured: a category’s highlighted rows. product: one product’s own page.',
            },
            applied: {
              type: 'object',
              properties: {
                min_price_eur: {
                  type: 'number',
                },
                max_price_eur: {
                  type: 'number',
                },
                sort: {
                  type: 'string',
                  enum: [
                    'relevance',
                    'price_asc',
                    'price_desc',
                    'biggest_price_drop',
                    'most_stores',
                    'newest',
                  ],
                },
                in_stock_only: {
                  type: 'boolean',
                  const: true,
                },
                deals_only: {
                  type: 'boolean',
                  const: true,
                },
              },
            },
            not_applied: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  constraint: {
                    type: 'string',
                    enum: ['min_price_eur', 'max_price_eur', 'sort', 'in_stock_only', 'deals_only'],
                  },
                  reason: {
                    type: 'string',
                    enum: ['not_offered', 'not_kept', 'no_product_list', 'no_products', 'page_unreadable'],
                    description:
                      'not_offered: see offered_sorts. no_product_list: an overview or one product’s page. page_unreadable: results unnarrowed.',
                  },
                  offered_sorts: {
                    type: 'array',
                    items: {
                      type: 'string',
                      enum: [
                        'relevance',
                        'price_asc',
                        'price_desc',
                        'biggest_price_drop',
                        'most_stores',
                        'newest',
                      ],
                    },
                  },
                },
                required: ['constraint', 'reason'],
              },
            },
            returned: {
              type: 'integer',
            },
            omitted_products: {
              type: 'integer',
            },
            products: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  product_id: {
                    type: 'string',
                    pattern: '^\\d{1,20}$',
                    description: 'Numeric BestPrice product id, as any tool returns it.',
                  },
                  title: {
                    type: 'string',
                  },
                  current_min_price_eur: {
                    type: 'number',
                    description: 'Lowest item price, before shipping.',
                  },
                  merchant_count: {
                    type: ['integer', 'null'],
                  },
                  store_offer: {
                    type: 'boolean',
                    const: true,
                    description: 'Links straight to its store; page tools never open it.',
                  },
                  store: {
                    type: 'string',
                  },
                  section: {
                    type: 'string',
                  },
                },
                required: ['product_id', 'title', 'current_min_price_eur', 'merchant_count'],
              },
            },
            navigated: {
              type: 'boolean',
            },
            next_step: {
              type: 'string',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
            note: {
              type: 'string',
            },
          },
          required: [
            'ok',
            'source',
            'query',
            'results_url',
            'page_title',
            'results_kind',
            'returned',
            'omitted_products',
            'products',
            'navigated',
            'next_step',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
            query: {
              type: 'string',
            },
            results_url: {
              type: 'string',
            },
            navigated: {
              type: 'boolean',
            },
            next_step: {
              type: 'string',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_visible_products: {
    title: 'Products on this page',
    description:
      'Read the products shown on this BestPrice listing or home page. Returns product_id, title, lowest price and store count, 8 per call. Use to see what the shopper sees; not for other products (use search_bestprice). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              enum: ['BestPrice listing page', 'BestPrice home page'],
            },
            total_results: {
              type: 'integer',
            },
            shown_products: {
              type: 'integer',
            },
            more_pages: {
              type: 'boolean',
              const: true,
              description: 'Pass load_more: true for the next page.',
            },
            returned: {
              type: 'integer',
            },
            products: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  product_id: {
                    type: 'string',
                    pattern: '^\\d{1,20}$',
                    description: 'Numeric BestPrice product id, as any tool returns it.',
                  },
                  title: {
                    type: 'string',
                  },
                  current_min_price_eur: {
                    type: 'number',
                    description: 'Lowest item price, before shipping.',
                  },
                  merchant_count: {
                    type: ['integer', 'null'],
                  },
                  store_offer: {
                    type: 'boolean',
                    const: true,
                    description: 'Links straight to its store; page tools never open it.',
                  },
                  store: {
                    type: 'string',
                  },
                  section: {
                    type: 'string',
                  },
                },
                required: ['product_id', 'title', 'current_min_price_eur', 'merchant_count'],
              },
            },
            offset: {
              type: 'integer',
            },
            omitted_products: {
              type: 'integer',
            },
            next_offset: {
              type: ['integer', 'null'],
              description: 'Pass as offset to continue; null at the end.',
            },
            completeness: {
              type: 'string',
              enum: ['complete', 'partial'],
            },
            note: {
              type: 'string',
            },
          },
          required: [
            'ok',
            'source',
            'shown_products',
            'returned',
            'products',
            'offset',
            'omitted_products',
            'next_offset',
            'completeness',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  open_visible_product: {
    title: 'Open a visible product',
    description:
      'Open a product shown on this BestPrice listing or home page by product_id. Returns it and whether the page confirmed the move (outcome). Use when the shopper picks one; not for unseen products (use get_product_details). Moves this tab.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            dispatched: {
              type: 'boolean',
            },
            applied: {
              type: 'boolean',
              description: 'Shown by the page itself.',
            },
            outcome: {
              type: 'string',
              enum: ['observed_complete', 'dispatched', 'unconfirmed'],
              description: 'dispatched: the tab moves after this answer. unconfirmed: read the page again.',
            },
            note: {
              type: 'string',
            },
            action: {
              type: 'string',
              enum: ['opened_visible_product', 'product_open_dispatched'],
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            title: {
              type: 'string',
            },
            bestprice_url: {
              type: 'string',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
          },
          required: [
            'ok',
            'dispatched',
            'applied',
            'outcome',
            'action',
            'product_id',
            'title',
            'bestprice_url',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_product_details: {
    title: 'Product details',
    description:
      'Read one BestPrice product by product_id; navigate: true moves this tab to it. Returns facts, price, top 4 offers, specs, price history. Use when you hold an id; not for finding (use search_bestprice) or choosing (use get_shopping_decision).',
    pageDescriptions: {
      product:
        'Read any BestPrice product by product_id, this one too; navigate: true moves this tab to it. Returns facts, price, top 4 offers, specs, price history. Use for an id from a search or pick; not for this page’s full offers (use compare_page_offers).',
    },
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice product page',
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            title: {
              type: 'string',
            },
            category: {
              type: 'string',
            },
            current_min_price_eur: {
              type: ['number', 'null'],
            },
            offer_count: {
              type: 'integer',
            },
            rating: {
              type: ['number', 'null'],
            },
            rating_count: {
              type: 'integer',
            },
            bestprice_url: {
              type: 'string',
            },
            offers: {
              description: 'Up to 4, known delivered price first; each: store, prices, availability, rating.',
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    compared: {
                      type: 'integer',
                    },
                    stores_total: {
                      type: ['integer', 'null'],
                    },
                    stores_considered: {
                      type: 'integer',
                    },
                    completeness: {
                      type: 'string',
                      enum: ['complete', 'partial'],
                    },
                    price_basis: {
                      type: 'string',
                      const: 'item_plus_shipping',
                    },
                    ranking_basis: {
                      type: 'string',
                      const: 'known_delivered_first_then_item_price',
                    },
                    payment_cost_status: {
                      type: 'string',
                      const: 'not_included',
                    },
                    items: {
                      type: 'array',
                      items: {
                        type: 'object',
                      },
                    },
                    omitted_offers: {
                      type: 'integer',
                    },
                    excluded_unknown_shipping: {
                      type: 'object',
                    },
                  },
                  required: [
                    'compared',
                    'stores_total',
                    'stores_considered',
                    'completeness',
                    'price_basis',
                    'ranking_basis',
                    'payment_cost_status',
                    'items',
                  ],
                },
                {
                  type: 'null',
                },
              ],
            },
            specifications: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    returned: {
                      type: 'integer',
                    },
                    total_facts: {
                      type: 'integer',
                    },
                    completeness: {
                      type: 'string',
                      enum: ['complete', 'partial'],
                    },
                    rows: {
                      type: 'array',
                      items: {
                        type: 'object',
                      },
                    },
                  },
                  required: ['returned', 'total_facts', 'completeness', 'rows'],
                },
                {
                  type: 'null',
                },
              ],
            },
            price_history: {
              description:
                'Price history: period, current, lowest, highest, directions; null when unreadable.',
              type: ['object', 'null'],
            },
            unavailable: {
              type: 'object',
              description: 'Why a requested section is null.',
              properties: {
                offers: {
                  type: 'string',
                },
                specifications: {
                  type: 'string',
                },
                price_history: {
                  type: 'string',
                },
              },
            },
            navigated: {
              type: 'boolean',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
            next_step: {
              type: 'string',
            },
            note: {
              type: 'string',
            },
          },
          required: [
            'ok',
            'source',
            'product_id',
            'title',
            'category',
            'current_min_price_eur',
            'offer_count',
            'rating',
            'rating_count',
            'bestprice_url',
            'navigated',
            'next_step',
            'note',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
            navigated: {
              type: 'boolean',
              const: true,
            },
            bestprice_url: {
              type: 'string',
              description: 'Where the tab moves, after this answer.',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
            next_step: {
              type: 'string',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_listing_filters: {
    title: 'Available filters',
    description:
      'List this BestPrice listing’s filters (brand, price, features) and their values. Returns up to 8 filters, 5 values each, selected ones marked. Use before apply_listing_filter; not for order (use get_listing_sort_options). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice listing filters',
            },
            total_results: {
              type: 'integer',
            },
            total_groups: {
              type: 'integer',
            },
            total_values: {
              type: 'integer',
            },
            filters: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  key: {
                    type: 'string',
                  },
                  name: {
                    type: 'string',
                  },
                  selected_values: {
                    type: 'array',
                    items: {
                      type: 'string',
                    },
                  },
                  available_values: {
                    type: 'array',
                    items: {
                      type: 'string',
                    },
                  },
                  ambiguous_values: {
                    type: 'integer',
                  },
                  collapsed_values: {
                    type: 'integer',
                  },
                  omitted_values: {
                    type: 'integer',
                  },
                },
                required: ['key', 'name', 'selected_values'],
              },
            },
            returned: {
              type: 'integer',
            },
            offset: {
              type: 'integer',
            },
            next_offset: {
              type: ['integer', 'null'],
              description: 'Pass as offset to continue; null at the end.',
            },
            omitted_values: {
              type: 'integer',
            },
            completeness: {
              type: 'string',
              enum: ['complete', 'partial'],
            },
            note: {
              type: 'string',
            },
          },
          required: ['ok', 'source', 'total_results', 'filters', 'returned', 'offset', 'next_offset'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  apply_listing_filter: {
    title: 'Apply a filter',
    description:
      'Narrow this BestPrice listing by one filter value, e.g. Κατασκευαστής: Samsung. Returns the value applied and whether the page confirmed it. Use with labels from get_listing_filters; not for clearing (use clear_listing_filters). Reloads the listing.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            action: {
              type: 'string',
              enum: ['applied_filter', 'filter_already_applied', 'filter_dispatched'],
            },
            filter: {
              type: 'string',
            },
            value: {
              type: 'string',
            },
            applied: {
              type: 'boolean',
              description: 'Shown by the page itself.',
            },
            dispatched: {
              type: 'boolean',
            },
            outcome: {
              type: 'string',
              enum: ['observed_complete', 'dispatched', 'unconfirmed'],
              description: 'dispatched: the tab moves after this answer. unconfirmed: read the page again.',
            },
            destination_url: {
              type: 'string',
              description: 'Where the tab moves, after this answer.',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
            note: {
              type: 'string',
            },
          },
          required: ['ok', 'action', 'filter', 'value'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  clear_listing_filters: {
    title: 'Clear filters',
    description:
      'Remove every filter from this BestPrice listing. Returns whether the page confirmed it (outcome), or filters_already_clear. Use when filters left too few products; not for adding one (use apply_listing_filter). Reloads the listing.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            action: {
              type: 'string',
              enum: ['cleared_listing_filters', 'clearing_filters_dispatched', 'filters_already_clear'],
            },
            changed: {
              type: 'boolean',
              const: false,
            },
            applied: {
              type: 'boolean',
              description: 'Shown by the page itself.',
            },
            dispatched: {
              type: 'boolean',
            },
            outcome: {
              type: 'string',
              enum: ['observed_complete', 'dispatched', 'unconfirmed'],
              description: 'dispatched: the tab moves after this answer. unconfirmed: read the page again.',
            },
            destination_url: {
              type: 'string',
              description: 'Where the tab moves, after this answer.',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
            note: {
              type: 'string',
            },
          },
          required: ['ok', 'action'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_listing_sort_options: {
    title: 'Available sorting options',
    description:
      'List the orders this BestPrice listing offers, e.g. «Φθηνότερα». Returns each option’s name and whether it is active. Use before apply_listing_sort; not for filters (use get_listing_filters). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice listing sorting',
            },
            returned: {
              type: 'integer',
            },
            sorting: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  name: {
                    type: 'string',
                  },
                  selected: {
                    type: 'boolean',
                  },
                },
                required: ['name', 'selected'],
              },
            },
          },
          required: ['ok', 'source', 'returned', 'sorting'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  apply_listing_sort: {
    title: 'Sort this product listing',
    description:
      'Reorder this BestPrice listing by one of its sort options. Returns the option applied and whether the page confirmed it. Use with a label from get_listing_sort_options; not for narrowing (use apply_listing_filter). Reloads the listing.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            action: {
              type: 'string',
              enum: ['applied_sorting', 'sorting_already_applied', 'sorting_dispatched'],
            },
            sort: {
              type: 'string',
            },
            applied: {
              type: 'boolean',
              description: 'Shown by the page itself.',
            },
            dispatched: {
              type: 'boolean',
            },
            outcome: {
              type: 'string',
              enum: ['observed_complete', 'dispatched', 'unconfirmed'],
              description: 'dispatched: the tab moves after this answer. unconfirmed: read the page again.',
            },
            destination_url: {
              type: 'string',
              description: 'Where the tab moves, after this answer.',
            },
            next_tools: {
              type: 'array',
              items: {
                type: 'string',
                pattern: '^[a-z][a-z0-9_]{0,63}$',
              },
              description: 'The destination page’s tools.',
            },
            note: {
              type: 'string',
            },
          },
          required: ['ok', 'action', 'sort'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_page_product: {
    title: 'Product details on this page',
    description:
      'Read the product on this BestPrice product page. Returns product_id, title, category, lowest price before shipping, offer count, rating and URL. Use first on a product page; not for delivered prices (use compare_page_offers). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice item page',
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            title: {
              type: 'string',
            },
            category: {
              type: 'string',
            },
            current_min_price_eur: {
              type: ['number', 'null'],
            },
            offer_count: {
              type: 'integer',
            },
            rating: {
              type: ['number', 'null'],
            },
            rating_count: {
              type: 'integer',
            },
            bestprice_url: {
              type: 'string',
            },
          },
          required: [
            'ok',
            'source',
            'product_id',
            'title',
            'category',
            'current_min_price_eur',
            'offer_count',
            'rating',
            'rating_count',
            'bestprice_url',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  compare_page_offers: {
    title: 'Compare offers on this page',
    description:
      'Compare the store offers on this BestPrice product page. Returns up to 4 offers, cheapest delivered first, with availability, store rating and offer_ref. Use when asked where to buy; not for specs (use get_product_specifications). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice item page',
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            compared: {
              type: 'integer',
            },
            stores_total: {
              type: ['integer', 'null'],
            },
            stores_considered: {
              type: 'integer',
            },
            completeness: {
              type: 'string',
              const: 'partial',
            },
            all_stores: {
              type: 'string',
              enum: ['unavailable', 'cancelled', 'failed', 'timeout'],
            },
            price_basis: {
              type: 'string',
              const: 'item_plus_shipping',
            },
            ranking_basis: {
              type: 'string',
              const: 'known_delivered_first_then_item_price',
            },
            payment_cost_status: {
              type: 'string',
              const: 'not_included',
            },
            offers: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  merchant: {
                    type: 'string',
                  },
                  product: {
                    type: 'string',
                  },
                  item_price_eur: {
                    type: 'number',
                  },
                  shipping_eur: {
                    type: ['number', 'null'],
                    description: 'null: unknown, never free.',
                  },
                  delivered_price_eur: {
                    type: ['number', 'null'],
                  },
                  availability: {
                    type: 'string',
                  },
                  merchant_rating: {
                    type: ['number', 'null'],
                  },
                  certified: {
                    type: 'boolean',
                  },
                  sponsored: {
                    type: 'boolean',
                  },
                  offer_ref: {
                    type: ['string', 'null'],
                    description: 'For show_offer.',
                  },
                  unpriced_rows: {
                    type: 'integer',
                  },
                  product_truncated: {
                    type: 'boolean',
                    const: true,
                  },
                  merchant_truncated: {
                    type: 'boolean',
                    const: true,
                  },
                },
                required: [
                  'merchant',
                  'product',
                  'item_price_eur',
                  'shipping_eur',
                  'delivered_price_eur',
                  'availability',
                  'merchant_rating',
                  'certified',
                  'sponsored',
                  'offer_ref',
                ],
              },
            },
            excluded_unknown_shipping: {
              type: 'object',
              description: 'Offers left out for unknown shipping; cheapest is shaped like offers[].',
              properties: {
                count: {
                  type: 'integer',
                },
                lowest_item_price_eur: {
                  type: 'number',
                },
                may_be_cheapest: {
                  type: 'boolean',
                  const: true,
                },
                cheapest: {
                  type: 'object',
                },
              },
              required: ['count', 'lowest_item_price_eur', 'cheapest'],
            },
            note: {
              type: 'string',
            },
          },
          required: [
            'ok',
            'source',
            'product_id',
            'compared',
            'stores_total',
            'stores_considered',
            'price_basis',
            'ranking_basis',
            'payment_cost_status',
            'offers',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_product_specifications: {
    title: 'Product specifications',
    description:
      'Read the specifications of the product on this BestPrice page: all, one section or one fact. Returns section, name and value rows, 16 per call. Use to check a feature; not for prices (use compare_page_offers). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice product specifications',
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            product_title: {
              type: 'string',
            },
            requested_section: {
              type: 'string',
            },
            requested_fact: {
              type: 'string',
            },
            note: {
              type: 'string',
            },
            returned: {
              type: 'integer',
            },
            omitted_facts: {
              type: 'integer',
            },
            total_facts: {
              type: 'integer',
            },
            offset: {
              type: 'integer',
            },
            next_offset: {
              type: ['integer', 'null'],
              description: 'Pass as offset to continue; null at the end.',
            },
            completeness: {
              type: 'string',
              enum: ['complete', 'partial'],
            },
            sections: {
              type: 'array',
              items: {
                type: 'string',
              },
            },
            continuation: {
              type: 'string',
            },
            specifications: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  section: {
                    type: 'string',
                  },
                  name: {
                    type: 'string',
                  },
                  value: {
                    type: 'string',
                  },
                  truncated: {
                    type: 'boolean',
                    const: true,
                  },
                },
                required: ['section', 'name', 'value'],
              },
            },
          },
          required: [
            'ok',
            'source',
            'product_id',
            'product_title',
            'requested_section',
            'returned',
            'omitted_facts',
            'completeness',
            'specifications',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  summarize_price_history: {
    title: 'Price history summary',
    description:
      'Summarize this product’s BestPrice price history. Returns current, lowest and highest prices, the period and the price direction with dates. Use when asked if now is a good time to buy; not for the chart (use show_price_history). Read-only.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice price history',
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            product_title: {
              type: 'string',
            },
            observations: {
              type: 'integer',
            },
            period: {
              type: 'object',
              properties: {
                from: {
                  type: 'string',
                },
                to: {
                  type: 'string',
                },
              },
              required: ['from', 'to'],
            },
            current_min_price_eur: {
              type: ['number', 'null'],
            },
            current_price_source: {
              type: 'string',
              enum: ['page_quote', 'latest_history'],
            },
            current_price_observed_at: {
              type: ['string', 'null'],
            },
            historical_low_eur: {
              type: ['number', 'null'],
            },
            historical_high_eur: {
              type: ['number', 'null'],
            },
            change_from_first_pct: {
              type: ['number', 'null'],
            },
            direction_from_first: {
              type: 'string',
              enum: ['up', 'down', 'stable', 'uncertain'],
            },
            latest_change_pct: {
              type: ['number', 'null'],
            },
            latest_direction: {
              type: 'string',
              enum: ['up', 'down', 'stable', 'uncertain'],
            },
            latest_change_since: {
              type: ['string', 'null'],
            },
            outliers_excluded: {
              type: 'integer',
            },
          },
          required: [
            'ok',
            'source',
            'product_id',
            'product_title',
            'observations',
            'period',
            'current_min_price_eur',
            'current_price_source',
            'current_price_observed_at',
            'historical_low_eur',
            'historical_high_eur',
            'change_from_first_pct',
            'direction_from_first',
            'latest_change_pct',
            'latest_direction',
            'latest_change_since',
            'outliers_excluded',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  show_offer: {
    title: 'Show an offer for this product',
    description:
      'Scroll this BestPrice product page to one store offer and highlight it. Returns the offer and whether it is in view. Use with an offer_ref from compare_page_offers; not for comparing (use compare_page_offers). Changes only what the shopper sees.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            action: {
              type: 'string',
              const: 'focused_offer',
            },
            offer_visible: {
              type: ['boolean', 'null'],
            },
            offer: {
              type: 'object',
              description: 'As compare_page_offers returns it.',
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
            note: {
              type: 'string',
            },
          },
          required: ['ok', 'action', 'offer_visible', 'offer', 'product_id', 'note'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  show_price_history: {
    title: 'Show this product price history',
    description:
      'Open or scroll to this BestPrice product page’s price-history chart. Returns which happened. Use when the shopper wants the chart; not for the numbers (use summarize_price_history). Changes only what the shopper sees.',
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            action: {
              type: 'string',
              enum: ['opened_price_history', 'focused_price_history'],
            },
            product_id: {
              type: 'string',
              pattern: '^\\d{1,20}$',
              description: 'Numeric BestPrice product id, as any tool returns it.',
            },
          },
          required: ['ok', 'action', 'product_id'],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
  get_shopping_decision: {
    title: 'Get a shopping decision',
    description:
      'Ask the BestPrice Shopping Brain (mcp.bestprice.gr) what to buy for stated needs. Returns a pick, alternatives, reasons, tradeoffs or a question. Use for advice; not for names (use search_bestprice) or a known id (use get_product_details). Read-only.',
    pageDescriptions: {
      product:
        'Ask the BestPrice Shopping Brain (mcp.bestprice.gr) what to buy for stated needs. Returns a pick, alternatives, reasons, tradeoffs or a question. Use for advice; not for names (use search_bestprice) or this product (use get_page_product). Read-only.',
    },
    outputSchema: {
      type: 'object',
      oneOf: [
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: true,
            },
            source: {
              type: 'string',
              const: 'BestPrice Shopping Brain',
            },
            outcome: {
              type: 'string',
              enum: ['recommendation', 'comparison', 'basket', 'clarification', 'no_match', 'answer'],
            },
            status: {
              type: 'string',
              enum: ['ready', 'no_match', 'needs_input'],
            },
            reason: {
              type: ['string', 'null'],
            },
            summary: {
              type: 'string',
            },
            clarifying_question: {
              type: ['string', 'null'],
            },
            recommended: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    product_id: {
                      type: 'string',
                      pattern: '^\\d{1,20}$',
                      description: 'Numeric BestPrice product id, as any tool returns it.',
                    },
                    title: {
                      type: 'string',
                    },
                    price_from_eur: {
                      type: ['number', 'null'],
                      description: 'Before shipping; not a quote.',
                    },
                    bestprice_url: {
                      type: 'string',
                      description: 'Signed; relay it verbatim.',
                    },
                    offer: {
                      type: 'object',
                    },
                  },
                  required: ['product_id', 'title', 'price_from_eur', 'bestprice_url'],
                },
                {
                  type: 'null',
                },
              ],
            },
            alternatives: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  product_id: {
                    type: 'string',
                    pattern: '^\\d{1,20}$',
                    description: 'Numeric BestPrice product id, as any tool returns it.',
                  },
                  title: {
                    type: 'string',
                  },
                  price_from_eur: {
                    type: ['number', 'null'],
                    description: 'Before shipping; not a quote.',
                  },
                  bestprice_url: {
                    type: 'string',
                    description: 'Signed; relay it verbatim.',
                  },
                  label: {
                    type: 'string',
                  },
                  tradeoff: {
                    type: ['string', 'null'],
                  },
                },
                required: ['product_id', 'title', 'price_from_eur', 'bestprice_url'],
              },
            },
            reasons: {
              type: 'array',
              items: {
                type: 'string',
              },
            },
            tradeoffs: {
              type: 'array',
              items: {
                type: 'string',
              },
            },
            unknowns: {
              type: 'array',
              items: {
                type: 'string',
              },
            },
            price_verdict: {
              type: ['string', 'null'],
              enum: ['good', 'typical', 'high', 'insufficient_evidence', null],
            },
            basket: {
              type: 'object',
              properties: {
                plan: {
                  type: 'string',
                  enum: ['cheapest', 'fewer_merchants', 'balanced'],
                },
                merchant_count: {
                  type: 'integer',
                },
                item_subtotal_eur: {
                  type: 'number',
                },
                total_eur: {
                  type: ['number', 'null'],
                },
                shipping_status: {
                  type: 'string',
                  enum: ['known', 'estimated', 'unknown', 'mixed'],
                },
              },
              required: ['plan', 'merchant_count', 'item_subtotal_eur', 'total_eur', 'shipping_status'],
            },
            catalog_candidates: {
              type: 'object',
              description:
                'no_match only: query, note and up to 4 products shaped like alternatives; not a recommendation.',
            },
            search_url: {
              type: 'string',
            },
            next_step: {
              type: 'string',
            },
            note: {
              type: 'string',
            },
          },
          required: [
            'ok',
            'source',
            'outcome',
            'status',
            'reason',
            'clarifying_question',
            'recommended',
            'alternatives',
            'reasons',
            'tradeoffs',
            'unknowns',
            'price_verdict',
            'next_step',
            'note',
          ],
        },
        {
          type: 'object',
          properties: {
            ok: {
              type: 'boolean',
              const: false,
            },
            error: {
              type: 'string',
            },
            reason: {
              type: 'string',
              pattern: '^[a-z0-9_]{1,64}$',
            },
          },
          required: ['ok', 'error'],
        },
      ],
    },
  },
};
